spring.datasource.url=jdbc:postgresql://localhost:5432/courierdb
spring.datasource.username=courier_app
spring.datasource.password=Courier@123
spring.mail.username=naveenkumarv@ctl-india.com
spring.mail.password=Panther@%$!#^
app.frontend-url=http://192.168.2.245:5173
