server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_USERNAME:admin}
      password: ${EUREKA_PASSWORD:admin123}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin123}@localhost:8761/eureka/

eureka.security:
  username: ${EUREKA_USERNAME:admin}
  password: ${EUREKA_PASSWORD:admin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info
